### ISSUE TITLE
Introduce the "division" concept

### ISSUE THREAD

**Issue by matejak** [EnterpriseyIntranet/teap#11]
An enterprisey organization has divisions and countries.
Divisions are somehow static, and they can be defined at startup.
To specify available divisions, consider either env variable (e.g. `DIVISIONS=Legal=LEG,Publishing=PUB,...`), or a config file (e.g. an `.ini` file). A division has a "machine name" and a "display name". For example, the Legal division can have display name `Legal`, and machine name `LEG`.

TEAP should be able to create division entries in the linked LDAP database (using EDAP), and it should be able to purge divisions that are in LDAP, and the currently running TEAP doesn't know about them. This should be always an on-demand operation, probably in a dedicated Divisions section  of the TEAP web app.

TEAP should also be able to create Nextcloud shared folders at `Divisions/<display name>`. Like that, the shared folder of the Legal division will be at `Divisions/Legal` (please notice the capitalization). The corresponding group owning the folder should be imported by Nextcloud from LDAP.
Everybody should have read access to all division folders, and users that are members of the division group will have read-write access.

A Rocketchat channel `Division <display name>` should be created for every division as a public, read-write channel. When a new user that belongs to the division is created, he should be added to it (if possible).

**Comment by danil-topc** [comment]
`and it should be able to purge divisions that are in LDAP, and the currently running TEAP doesn't know about them`
Looks like EDAP doesn't have removing objects possibility rn, should I implement it there first ?

**Comment by matejak** [comment]
Yes, this is a great observation, go ahead and proceed with the implementation!

**Comment by matejak** [comment]
Basically done, thanks!
