### ISSUE TITLE
Introduce the Country/team concept.

### ISSUE THREAD

**Issue by matejak** [EnterpriseyIntranet/teap#14]
As mentioned in #11, an enterprisey organization has divisions and countries.
Countries may be added to the organization gradually.

TEAP should be able to create country entries in the linked LDAP database (using EDAP), and it should be able to read the database to understand what countries are known. There should be an interface for adding a new country.
When a new country is created, an LDAP entry is created for it, and team entries are created as well, so there are teams for every `<new country>-<division>` combination.

TEAP should also be able to create Nextcloud shared folders at Countries/<display name>. Like that, the shared folder for Poland will be at Countries/Poland. The corresponding group owning the folder should be imported by Nextcloud from LDAP.
Everybody should have read access to all countries folders, and users that are members of the country group will have read-write access.

A typical new user will be added to a team. The TEAP app should be able to put him to the team group and to respective country and division groups.
For example, if Janusz is added to the Polish Publishing team, he is "silently" added into the Poland and Publishing groups, so he has correct access rights to folders.

A Rocketchat channel Country <display name> should be created for every country as a public, read-write channel. When a new user that belongs to the country is created, he should be added to it (if possible).

**Comment by danil-topc** [comment]
@matejak am I understand it right - countries are separate organizational unit in top level as divisions ? Or they are `ou=franchises` ?

**Comment by danil-topc** [comment]
> When a new country is created, an LDAP entry is created for it, and team entries are created as well, so there are teams for every <new country>-<division> combination
Teams mean in division organizational unit, right ? And another way - if new division is created, the team for every country should be created as well ?

**Comment by matejak** [comment]
> Teams mean in division organizational unit, right ?
In EDAP, teams could be another org unit.
> And another way - if new division is created, the team for every country should be created as well ?
Yes, this is correct. When another franchise is created, all teams should be created as well.

**Comment by danil-topc** [comment]
> In EDAP, teams could be another org unit.

But if we have for example franchise with `machine_name='ua'`, `display_name='Ukraine'`, I should create team for every division we have, for example `IT` division, which will be `IT-Ukraine`. If yes, how to show or may be filter these divisions on divisions page, where they will be in `Ldap only divisions` column.

**Comment by matejak** [comment]
I have reviewed this issue, and there are following outstanding subtasks:

- As there are sub-pages for `Divisions` and `Franchises`, one for `Teams` would be great.
- Support for new users - when a user is added to a team, it gets added to the respective division and franchise automatically.

**Comment by danil-topc** [comment]
> As there are sub-pages for Divisions and Franchises, one for Teams would be great.

Added sub-page.

> Support for new users - when a user is added to a team, it gets added to the respective division and franchise automatically.

It works right now on user edit page. 
On user creation page there is old selector for groups without this logic implemented, I should probably delete it in next PRs. So user will be created at first, then redirected to user page with possibility to add to teams, is that ok ?

**Comment by matejak** [comment]
This is now fully operational.
