### ISSUE TITLE
Adding an existing user to a franchise does not always work

### ISSUE THREAD

**Issue by matejak** [EnterpriseyIntranet/teap#27]
How to reproduce:

on teap.entint.org, when I add a user to Switzerland, the Rocketchat request fails, as the franchise group doesn't exist for some reason. The Nextcloud part doesn't fail, but there is no franchise folder upon login.

If a franchise is "incomplete", i.e. it has an LDAP entry, but no folders/rooms, it should be "completed" before TEAP attempts to add user to a room.

**Comment by danil-topc** [comment]
Fixed in #28
